In [11]:
import numpy as np

In [12]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b=np.array([[1.0,2,3],[4.5,5.3,2]])
print(b)

[[1.  2.  3. ]
 [4.5 5.3 2. ]]


In [14]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [15]:
#number of elements
print(a.size)
print(b.size)

3
6


In [16]:
print(a.ndim)
print(b.ndim)

1
2


In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# Get a specific element [r, c]
a[1, 5]

13

In [19]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [22]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [27]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [32]:
# Any other number (full_like)
np.full_like(a, 8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [33]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.62167266, 0.88274773],
       [0.46673943, 0.8650876 ],
       [0.33252332, 0.5298586 ],
       [0.32689241, 0.54109973]])

In [36]:
# Random Integer values
np.random.randint(-14,8, size=(3,3))

array([[-11,  -3, -10],
       [ -5, -11, -14],
       [  3,  -8,  -4]])

In [37]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
#
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [43]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [44]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [45]:
b = np.array([1,0,1,0])
a + b


array([2, 2, 4, 4])

In [46]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [47]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [49]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [50]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.min(stats)

1

In [53]:
# axis=0 for rows axis=1 for columns
np.max(stats, axis=0)


array([4, 5, 6])

In [54]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [57]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])